data work.project;
infile 'C:\Users\samsung\Desktop\SAS_VM.txt';
input x;
run;
proc print data=work.project;
run;
proc print data=work.project;
run;
proc freq data=work.project;
run;
proc print data=work.project;
run;
proc freq data=work.project;
table x;
run;
proc freq data=work.project;
table x /nocum nopercent;
run;
ods pdf file='C:\Users\samsung\Desktop\SAS_VM.txt';
proc means data=work.project;
run;
ods pdf close;
